#!/usr/bin/env python3
"""Convert the Go sprite sources (sprites_data.go, tile_sprites.go) into src/engine/art.gen.ts.

One-shot: run once against the Go files at commit d21ac55, commit the output, then the Go files go.
Output format (TypeScript):
  PALETTE: string[]                       every distinct '#RRGGBB' used by tile/furniture sprites
  TILE_SPRITES: Record<name, string[]>    16 rows of 32 chars: 2 hex digits per pixel (TILE_PALETTE index), '..' transparent
  CHAR_TEMPLATES: Record<name, string[]>  rows of template keys: . H K S P O E
  CHAR_PALETTES: {skin,shirt,pants,hair,shoes}[]
"""
import re, sys, json

B62 = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'

def strip_comments(src):
    return re.sub(r'//[^\n]*', '', src)

def var_aliases(src):
    aliases = {}
    for m in re.finditer(r'var\s+([\w\s,]+?)\s*=\s*("#[0-9A-Fa-f]{6}"(?:\s*,\s*"#[0-9A-Fa-f]{6}")*)', src):
        names = [n.strip() for n in m.group(1).split(',')]
        vals = re.findall(r'"(#[0-9A-Fa-f]{6})"', m.group(2))
        if len(names) == len(vals):
            aliases.update(dict(zip(names, vals)))
    for m in re.finditer(r'^\s*(\w+)\s*=\s*"(#[0-9A-Fa-f]{6})"', src, re.M):  # inside var ( ... ) blocks
        aliases.setdefault(m.group(1), m.group(2))
    return aliases

def blocks(src, typ):
    # var NAME = Sprite{ ... }  /  var NAME = [][]string{ ... }  — balanced-brace scan
    out = {}
    for m in re.finditer(r'var\s+(\w+)\s*=\s*' + re.escape(typ) + r'\{', src):
        i, depth = m.end(), 1
        while depth:
            depth += {'{': 1, '}': -1}.get(src[i], 0)
            i += 1
        body = src[m.end():i - 1]
        rows = re.findall(r'\{([^{}]*)\}', body)
        out[m.group(1)] = [[t.strip() for t in r.split(',') if t.strip()] for r in rows]
    return out

def main(sprites_go, tiles_go, wall_go, out_ts):
    tiles_src = strip_comments(open(tiles_go).read())
    wall_src = strip_comments(open(wall_go).read())
    chars_src = strip_comments(open(sprites_go).read())
    aliases = {**var_aliases(wall_src), **var_aliases(tiles_src)}
    palette, index = [], {}
    def idx(color):
        c = color.upper()
        if c not in index:
            index[c] = len(palette); palette.append(c)
        return index[c]
    tile_sprites = {}
    for name, rows in blocks(tiles_src, 'Sprite').items():
        enc = []
        for row in rows:
            s = ''
            for tok in row:
                if tok == '""':
                    s += '..'
                    continue
                color = tok.strip('"') if tok.startswith('"') else aliases.get(tok)
                if not color:
                    sys.exit(f'{name}: unknown token {tok!r}')
                s += format(idx(color), '02x')
            enc.append(s)
        if len(enc) < 16 and all(len(r) == 32 for r in enc):
            # The playroom branch's couch has 15 rows; Go drew it short. Pad with transparency, keep going.
            print(f'warning: {name} has {len(enc)} rows, padded to 16 with transparent rows', file=sys.stderr)
            enc += ['..' * 16] * (16 - len(enc))
        if len(enc) != 16 or any(len(r) != 32 for r in enc):
            sys.exit(f'{name}: expected 16x16, got {len(enc)}x{[len(r) for r in enc]}')
        tile_sprites[re.sub(r'^sprite|Sprite$', '', name)[:1].lower() + re.sub(r'^sprite|Sprite$', '', name)[1:]] = enc
    if len(palette) > 255:
        sys.exit(f'palette too big: {len(palette)}')
    keymap = {'t_': '.', 'tH': 'H', 'tK': 'K', 'tS': 'S', 'tP': 'P', 'tO': 'O', 'tE': 'E'}
    templates = {}
    for name, rows in blocks(chars_src, '[][]string').items():
        if not name.startswith('char'):
            continue
        enc = [''.join(keymap[t] for t in row) for row in rows]
        if len(enc) != 24 or any(len(r) != 16 for r in enc):
            sys.exit(f'{name}: expected 16x24, got {len(enc)} rows')
        templates[name[4].lower() + name[5:]] = enc
    pals = [dict(zip(['skin', 'shirt', 'pants', 'hair', 'shoes'], m)) for m in
            re.findall(r'\{Skin:\s*"(#\w+)",\s*Shirt:\s*"(#\w+)",\s*Pants:\s*"(#\w+)",\s*Hair:\s*"(#\w+)",\s*Shoes:\s*"(#\w+)"\}', chars_src)]
    with open(out_ts, 'w') as f:
        f.write('// Generated by tools/convert-art.py from the Go sprite sources (pixel-agents-tui d21ac55).\n')
        f.write('// Art derived from pablodelucca/pixel-agents, MIT. Do not edit by hand; extend in art.ts.\n\n')
        f.write('export const TILE_PALETTE: readonly string[] = ' + json.dumps(palette) + '\n\n')
        f.write('export const TILE_SPRITES: Readonly<Record<string, readonly string[]>> = ' + json.dumps(tile_sprites, indent=2) + '\n\n')
        f.write('export const CHAR_TEMPLATES: Readonly<Record<string, readonly string[]>> = ' + json.dumps(templates, indent=2) + '\n\n')
        f.write('export const CHAR_PALETTES = ' + json.dumps(pals, indent=2) + ' as const\n')
    print(f'palette={len(palette)} tiles={sorted(tile_sprites)} templates={len(templates)} palettes={len(pals)}')

if __name__ == '__main__':
    main(*sys.argv[1:5])
